hack/install_cli.sh

* simplified script for public repo
* show install progress for wget

chore: improve cli install script

---

LICENSE.txt

Add a license for kubeblocks

---

README.md

chore: improve kbcli readme

---

README.md

* resolve https://github.com/apecloud/kubeblocks/issues/3401

feat: add yum install kbcli doc

---

.github/utils/issue_prerelease.sh

fix: add issue_prerelease.sh

---

Makefile

fix: fix make kbcli-doc fail in CI

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli.md
docs/user_docs/cli/kbcli_cluster_create.md
docs/user_docs/cli/kbcli_cluster_create_orioledb.md
docs/user_docs/cli/kbcli_cluster_create_qdrant.md
pkg/cmd/auth/login.go
pkg/cmd/cli.go
pkg/cmd/context/cloud_context.go
pkg/cmd/context/cloud_context_test.go
pkg/cmd/organization/cloud_organization.go
pkg/cmd/organization/organization.go

This PR is a cherry-pick of the CLI content that was merged into KubeBlocks during the repository split.
- fix: #30 
- relate https://github.com/apecloud/kubeblocks/pull/5801

feat: cherry-pick #5801 in Kubeblocks

---

go.mod
go.sum
pkg/cmd/cluster/create.go
pkg/cmd/cluster/dataprotection.go

This PR is a cherry-pick of the CLI content that was merged into KubeBlocks during the repository split.
- fix: #30 
- relate https://github.com/apecloud/kubeblocks/pull/5794

feat: cherry-pick #5794 in Kubeblocks

---

go.mod
go.sum
pkg/cmd/backuprepo/backuprepo.go
pkg/cmd/backuprepo/common.go
pkg/cmd/backuprepo/create.go
pkg/cmd/backuprepo/describe.go
pkg/cmd/backuprepo/describe_test.go
pkg/cmd/backuprepo/list.go
pkg/cmd/backuprepo/list_test.go
pkg/cmd/backuprepo/update.go
pkg/cmd/backuprepo/update_test.go

This PR is a cherry-pick of the CLI content that was merged into KubeBlocks during the repository split.
- fix: #30 
- relate: https://github.com/apecloud/kubeblocks/pull/5803

feat: cherry-pick #5803 in Kubeblocks

---

pkg/util/git.go

fix: fix kbcli addon index update always latest

---

pkg/cmd/cluster/operations.go
pkg/cmd/cluster/operations_test.go
pkg/testing/fake.go
pkg/types/types.go

related KubeBlocks PR: https://github.com/apecloud/kubeblocks/pull/5907

chore: switchover ops with component definition api

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli_addon.md
pkg/cmd/addon/addon.go
pkg/cmd/addon/index.go
pkg/cmd/addon/index_test.go
pkg/cmd/addon/install.go
pkg/cmd/addon/install_test.go
pkg/cmd/addon/uninstall.go
pkg/cmd/addon/upgrade.go
pkg/cmd/addon/upgrade_test.go
pkg/cmd/cluster/label.go
pkg/testing/fake.go
pkg/types/types.go

feat: support addon install/uninstall/upgrade

---

pkg/cluster/helper.go
pkg/cmd/accounts/base.go
pkg/cmd/cluster/operations.go

fix: create-account failed to locate primary pod

---

pkg/cmd/addon/index.go
pkg/cmd/addon/search.go
pkg/cmd/addon/search_test.go
pkg/cmd/addon/uninstall.go
pkg/cmd/addon/upgrade.go

chore: fix addon output

---

docs/user_docs/cli/kbcli_cluster_create.md
pkg/cluster/cluster.go
pkg/cluster/types.go
pkg/cmd/addon/install_test.go
pkg/cmd/cluster/connect.go
pkg/cmd/cluster/connect_test.go

- fix https://github.com/apecloud/kubeblocks/issues/5952

feat: support to connect with componetdefinition cluster 

---

pkg/cmd/backuprepo/update.go
pkg/cmd/backuprepo/update_test.go

fix: failed to update backup repo

---

go.mod
go.sum

- fix: https://github.com/apecloud/kubeblocks/issues/6286

fix: upgrade kb version

---

go.mod
go.sum

chore: support connect to Oracle

---

pkg/cmd/cluster/connect.go
pkg/testing/fake.go

fix: disable connect polardbx

---

pkg/cmd/cluster/connect.go

fix: fix connect nebula error

---

pkg/cluster/helper.go

fix: account mgr with componentDef err

---

docs/user_docs/cli/kbcli_backuprepo_create.md
go.mod
go.sum
pkg/cmd/backuprepo/create.go
pkg/cmd/cluster/config_observer.go
pkg/testing/fake.go

ref to https://github.com/apecloud/kubeblocks/pull/6874

chore: add "--path-prefix" flag to backuprepo create command

---

CONTRIBUTING.md
README.md

Added a CONTRIBUTING.md files with the proper steps required to set up the project on the local system.
Fixes #278 
cc - @shanshanying / @TalktoCrystal

docs: add a CONTRIBUTING.md file for kbcli repo

---

docs/user_docs/cli/kbcli_cluster_configure.md
pkg/cmd/cluster/config_ops.go

* fix https://github.com/apecloud/kbcli/issues/310

fix: sample code for the cluster section

---

docs/user_docs/cli/kbcli_cluster_edit-config.md
pkg/cmd/cluster/config_edit.go
pkg/cmd/cluster/errors.go

docs: fix typos

---

docs/user_docs/cli/kbcli_cluster_create.md
docs/user_docs/cli/kbcli_cluster_create_qdrant.md
docs/user_docs/cli/kbcli_cluster_create_rabbitmq.md
docs/user_docs/cli/kbcli_cluster_custom-ops.md
pkg/cmd/kubeblocks/uninstall.go

* fix https://github.com/apecloud/kbcli/issues/542

chore: do not remove kubeblocks repo when uninstall kb

---

pkg/cmd/cluster/create_subcmds.go

fix: remove useless line

---

pkg/cmd/kubeblocks/data/kubeblocks_base_preflight.yaml

chore: add volumesnapshot check to preflight

---

pkg/cmd/kubeblocks/data/kubeblocks_base_preflight.yaml

This reverts commit 3d909fcb07a2adc169dd6a1e32676ecca962f282.

Revert "chore: add volumesnapshot check to preflight (#611)"
