apecloud/kbcli

pkg/cmd/cli.go
pkg/types/types.go
pkg/util/log.go
pkg/util/util.go

```
ll ~/.kbcli/logs
total 8
-rw-r--r--  1 ldm  staff   786B Nov 14 10:06 kbcli-2023-11-14.log
```

chore: add logs dir to store kbcli log

---

pkg/cmd/kubeblocks/upgrade.go

* resolve [#32 ](https://github.com/apecloud/kbcli/issues/40)

feat: only stop kubeblocks when kubeblocks version is specified

---

go.mod
go.sum

- relate https://github.com/apecloud/kubeblocks/issues/5848 and https://github.com/apecloud/kubeblocks/issues/5855
fix the KB version in kbcli go.mod

chore: fix KB version

---

docs/user_docs/cli/kbcli_cluster_create_llm.md
pkg/cmd/auth/login.go
pkg/cmd/cluster/connect.go

fix: kbcli cluster connect use root credential

---

docs/user_docs/cli/kbcli_cluster_create_llm.md
docs/user_docs/cli/kbcli_clusterdefinition_list-service-reference.md
pkg/cmd/cluster/create.go
pkg/cmd/clusterdefinition/list_service_reference.go

fix `kbcli clusterdefinition list-service-reference` usage and `kbcli cluster create` error msg

chore: fix usage and error msg

---

docs/user_docs/cli/kbcli_cluster_create_llm.md
pkg/cmd/auth/login.go
pkg/cmd/kubeblocks/install.go
pkg/cmd/kubeblocks/upgrade.go
pkg/util/util.go
pkg/util/util_test.go

* fix https://github.com/apecloud/kubeblocks/issues/5943

chore: kb install/upgrade handle version with v prefix

---

.gitignore
docs/user_docs/cli/kbcli_cluster_custom-ops.md
docs/user_docs/cli/kbcli_cluster_edit-config.md
pkg/action/template/cluster_operations_template.cue
pkg/cmd/cluster/config_edit.go
pkg/cmd/cluster/config_ops.go
pkg/cmd/cluster/describe_ops.go

**Simplify reconfigure operation of clickhouse and mongodb multi-sharding engines**
feat: [[Features] reconfigure operation support multi components #5906](https://github.com/apecloud/kubeblocks/issues/5906)
related pr: https://github.com/apecloud/kubeblocks/pull/5994
e.g: kbcli cluster edit-config ch --components=shard-0,shard-1,shard-2

chore: support reconfigure operation for multi components (#5906)

---

pkg/cmd/addon/addon.go
pkg/cmd/cli.go
pkg/types/types.go

fix: do not set default image registry

---

go.mod
pkg/cmd/addon/addon.go
pkg/cmd/cluster/operations.go
pkg/cmd/kubeblocks/install.go

- fix https://github.com/apecloud/kubeblocks/issues/6120
fix two promble:
1.  viper env not be persisted
2. viper.Get will return nil when the key not be found

fix: fix image.registry env not be persisted

---

pkg/cmd/cli.go

- fix https://github.com/apecloud/kubeblocks/issues/6147

fix: output redundant config info

---

pkg/cmd/kubeblocks/install.go
pkg/cmd/kubeblocks/uninstall.go
pkg/cmd/kubeblocks/upgrade.go
pkg/cmd/kubeblocks/util.go

Remove all addons when uninstall KubeBlocks.

chore: remove all addons when uninstall KubeBlocks

---

docs/user_docs/cli/kbcli_addon_list.md
pkg/cmd/addon/addon.go
pkg/types/types.go

```shell
./bin/kbcli addon list --status=enabled 
NAME                  VERSION         PROVIDER    STATUS    AUTO-INSTALL   
apecloud-mysql        0.8.0-beta.3    apecloud    Enabled   true           
kafka                 0.8.0-alpha.5   community   Enabled   true           
mongodb               0.7.0           apecloud    Enabled   true           
postgresql            0.8.0-alpha.5   community   Enabled   true           
pulsar                0.7.0           community   Enabled   true           
redis                 0.8.1           community   Enabled   true           
snapshot-controller   1.7.2           community   Enabled   true     
./bin/kbcli addon list --engines 
NAME             VERSION         PROVIDER    STATUS     AUTO-INSTALL   
clickhouse       0.7.0 …
```

chore: addon list support only show by status or show engines addon

---

docs/user_docs/cli/kbcli_cluster_edit-backup-policy.md
go.mod
go.sum
pkg/cmd/builder/template/component_wrapper.go
pkg/cmd/cluster/dataprotection.go
pkg/cmd/cluster/dataprotection_test.go

Ref: https://github.com/apecloud/kubeblocks/pull/6723
Usage:
```
kbcli cluster edit-backup-policy <backup-policy-name> --set encryption.algorithm=AES-256-CFB --set encryption.passPhrase="SECRET!"
kbcli cluster edit-backup-policy <backup-policy-name> --set encryption.disabled=true
```

feat: edit-backup-policy supports backup encryption configuration

---

pkg/cmd/cluster/dataprotection.go

fix: check if the specified backup method exists when creating a backup

---

pkg/cmd/version/version.go
pkg/cmd/version/version_test.go

fix: Raise the version constraint of KBCLI and KB (#300)

---

pkg/cmd/backuprepo/common.go
pkg/cmd/cluster/dataprotection.go
pkg/cmd/cluster/dataprotection_test.go

check existence of backuprepo before creating a backup

fix: check existence of backuprepo before creating a backup

---

pkg/cmd/kubeblocks/kubeblocks_objects.go
pkg/cmd/kubeblocks/util.go

After the upgrade, the storage version of configconstraint will be adjusted to v1beta1. When kubeblocks uninstall is deleted, the deletion of the v1alpha1 version will trigger apiserver multi version conversion. Because the webhook is not enabled, the fields of the converted v1beta1 version will be missing.

fix: kbcli uninstall kubeblocks fail (#7646)

---

Makefile

Command `kbcli playground init` depends on this variable, a newer version of k8s cluster can avoid errors caused by outdated fields in addon Helm charts during kubeblocks installation.
fix #397 #196

fix: update default k3s version in makefile

---

docs/user_docs/cli/kbcli_cluster_create_elasticsearch.md
pkg/cmd/cluster/connect.go

fix: fix cluster connect --show-example

---

pkg/cmd/cluster/create_subcmds.go
pkg/cmd/cluster/create_subcmds_test.go

fix #428
Change
- Support verifying componnetDef from shardingSpecs of Cluster.
Test
- After fixed, a redis cluster of mode "cluster" can be created correctly.
1. Edit go build configuration.
2. Run kbcli with create commands and get result.
3. Check the phase of redis cluster.

fix: support create sharding cluster

---

docs/user_docs/cli/kbcli_kubeblocks_install.md
docs/user_docs/cli/kbcli_kubeblocks_upgrade.md
pkg/cmd/kubeblocks/compare.go
pkg/cmd/kubeblocks/install.go
pkg/cmd/kubeblocks/upgrade.go
pkg/cmd/report/zipwritter.go
pkg/preflight/analyzer/kb_taint.go

* ref https://github.com/apecloud/kubeblocks/pull/8099

chore: delete deploy when upgrade

---

docs/user_docs/cli/kbcli_cluster_restore.md
docs/user_docs/cli/kbcli_dataprotection_restore.md
go.mod
go.sum
pkg/cmd/cluster/create.go
pkg/cmd/cluster/dataprotection.go
pkg/cmd/dataprotection/restore.go
pkg/util/breakingchange/upgradehandlerto0.7.go

Resolve https://github.com/apecloud/kubeblocks/issues/8128
Add two flags `--restore-key` and `--restore-key-ignore-errors`  to support Redis restore by keys

feat: restore-by-keys

---

docs/user_docs/cli/kbcli_addon_install.md
docs/user_docs/cli/kbcli_addon_search.md
docs/user_docs/cli/kbcli_addon_upgrade.md
docs/user_docs/cli/kbcli_cluster_register.md
pkg/cluster/external_charts.go
pkg/cluster/register_test.go
pkg/cmd/addon/addon.go
pkg/cmd/addon/install.go
pkg/cmd/addon/install_test.go
pkg/cmd/addon/search.go
pkg/cmd/addon/search_test.go
pkg/cmd/addon/uninstall.go
pkg/cmd/addon/upgrade.go
pkg/cmd/addon/util.go
pkg/cmd/cluster/register.go
pkg/cmd/cluster/register_test.go
pkg/types/types.go
pkg/util/helm/helm.go

partly fixed: #420
what's changed:
1. Cluster register supports overriding the built-in chart, pulling by helm repo + engine + version, and validating schema standards.
2. Addon install and search support specifying a local path.
3. Addon install, enable, and upgrade support register the chart at the same time.
4. Addon uninstall also deletes the corresponding chart.
5. Addon search supports searching for all addons (including those not installed).

feat: imporve cluster register and addon

---

Makefile

compare charts, not only rendered cluster.yaml.

chore: udpate Makefile on buiding embeding charts

---

pkg/cmd/kubeblocks/upgrade.go
pkg/cmd/kubeblocks/upgrade_test.go
pkg/util/helm/helm.go
pkg/util/helm/helm_test.go

fix #398
Refer to [helm upgrade](https://github.com/helm/helm/blob/e81f6140ddb22bc99a08f7409522a8dbe5338ee3/pkg/action/upgrade.go#L204-L224)
Check the release status of Kubeblocks before upgrade. Upgrade will run correctly only if the status is one of 'deployed', 'failed' and 'superseded' .

feat: check helm release status before kubeblocks upgrade

---

docs/user_docs/cli/kbcli_addon_install.md
docs/user_docs/cli/kbcli_addon_search.md
pkg/cmd/addon/install.go
pkg/cmd/addon/search.go
pkg/cmd/addon/upgrade_test.go
pkg/util/breakingchange/upgradehandlerto0.7.go

* resolve https://github.com/apecloud/kbcli/issues/456
```
bin/kbcli addon install mysql
error: required flag(s) "version" not set
bin/kbcli addon install mysql --version=""
error: please specify the version, run 'kbcli addon search mysql' to get the available versions
```

feat: addon install require to specify the version

---

pkg/cmd/addon/addon.go

fix cluster chart version when auto register, use the version in Label.

chore: fix cluster chart version when auto register

---

docs/user_docs/cli/kbcli_cluster_create_elasticsearch.md
pkg/cmd/cluster/create_subcmds.go
pkg/cmd/cluster/create_util.go
pkg/cmd/cluster/create_util_test.go

(cherry picked from commit 0079f563a06a687536dbfdebc039c5d1490f28cb)

chore: enable rbac by default for elasticsearch (#460)

---

docs/user_docs/cli/kbcli_playground_init.md
pkg/cmd/cluster/cluster_test.go
pkg/cmd/cluster/create_subcmds.go
pkg/cmd/cluster/create_subcmds_test.go
pkg/cmd/playground/destroy.go
pkg/cmd/playground/init.go
pkg/cmd/playground/init_test.go
pkg/cmd/playground/types.go
pkg/testing/fake.go

fix #459
What's changed?
1. add ut of `cluster create`.
2. adapt `playground init` to new create cmd.
3. `playground init` delete specifying cloud-provider, only support k3d locally.

feat: playground only support k3d

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli.md
pkg/cmd/cli.go
pkg/cmd/clusterdefinition/describe.go
pkg/cmd/componentdefinition/componnetdefinition.go
pkg/cmd/componentdefinition/describe.go
pkg/cmd/componentversion/describe.go
pkg/cmd/opsdefinition/describe.go
pkg/cmd/opsdefinition/opsdefinition.go
pkg/cmd/opsdefinition/opsdefinition_test.go
pkg/cmd/opsdefinition/suite_test.go

what's changed?
support `kbcli  ops-definition/ops-def  list/ls` and `kbcli  ops-definition/ops-def  describe/desc`

chore: support ops-def list and describe

---

pkg/cmd/cluster/operations.go

fix https://github.com/apecloud/kubeblocks/issues/8478

fix: specifying namespace on ops cmds.

---

pkg/cmd/kubeblocks/upgrade.go
pkg/cmd/kubeblocks/upgrade_test.go
pkg/util/helm/errors.go
pkg/util/helm/helm.go
pkg/util/helm/helm_test.go

move checking upgrade release status from kubeblocks/upgrade() to helm/upgrade() and improve UT.

chore: fix check upgrade release status

---

docs/user_docs/cli/kbcli_cluster_custom-ops.md
docs/user_docs/cli/kbcli_cluster_start.md
docs/user_docs/cli/kbcli_cluster_stop.md
pkg/action/template/cluster_operations_template.cue
pkg/cmd/cluster/operations.go
pkg/cmd/cluster/register.go

cluster stop and start support components.
Change flags of these two commands, and modify the .cue file to render the opsRequest.

chore: cluster stop and start support components

---

docs/user_docs/cli/kbcli_playground_init.md
pkg/cloudprovider/k3d.go
pkg/cloudprovider/k3d_test.go
pkg/cloudprovider/suite_test.go
pkg/cloudprovider/types.go
pkg/cmd/cluster/operations.go
pkg/cmd/cluster/register_test.go
pkg/cmd/playground/init.go
pkg/cmd/playground/suite_test.go

fix #488
* `playground init `support specifying k3s and k3d-proxy images by two flags `--k3s-image` and `--k3d-proxy-image`.  
* For example, you can use `kbcli playground init --k3d-proxy-image=registry.aliyuncs.com/apecloud/k3d-proxy:5.4.4` to specify the image of k3d-proxy. 
* fix a bug of remaining test file after running ut in cmd/cluster.

chore: playground init support specifying k3s and k3d-proxy images.

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli_dataprotection.md
docs/user_docs/cli/kbcli_dataprotection_backup.md
docs/user_docs/cli/kbcli_dataprotection_list-backups.md
pkg/cmd/dataprotection/actionset.go
pkg/cmd/dataprotection/backup.go
pkg/cmd/dataprotection/backuppolicy.go
pkg/cmd/dataprotection/backuppolicytemplate.go
pkg/cmd/dataprotection/datatprotection_test.go
pkg/cmd/dataprotection/restore.go

fix #510
list-backup --> list-backups
list-action-set --> list-action-sets
list-backup-policy --> list-backup-policies
list-backup-policy-template --> list-backup-policy-templates
list-restore --> list-restores

fix: improve typo of list cmd in dataprotection

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli_addon.md
pkg/cmd/addon/addon.go
pkg/cmd/addon/delete_resource.go
pkg/cmd/addon/delete_resource_test.go
pkg/cmd/addon/uninstall.go
pkg/cmd/addon/uninstall_test.go

fix #441
usage:
add a cmd `kbcli addon delete-resources-with-version [addonName] --versions= or --all-unused-versions=`
example:
`kbcli addon delete-resources-with-version postgresql --versions=0.9.1` 
` kbcli addon delete-resources-with-version postgresql --all-unused-versions=true` 
effect:
clean resources which are belong to the specified addon, and not the newest version defined in the helm release, and not currently used by any cluster.
By far, the reource type will be checked and cleaned are `types.CompDefGVR(),
types.ConfigmapGVR(),
types.ConfigConstraintGVR(),
types.ConfigConstraintOldGVR(),`

feat: addon support clean sub-resource of multi-versions

---

docs/user_docs/cli/kbcli_cluster_list.md
pkg/action/list.go
pkg/cluster/printer.go
pkg/cmd/cluster/list.go
pkg/cmd/cluster/list_test.go

fix #448
what's changed?
1. improve order of cluster list, now the sort order is namespace、clusterDefinition、 status、 name.
2. add a flag of cluster list to specify the status to filter.
usage:
`kbcli cluster list --status=Running`

feat: improve cluster list

---

docs/user_docs/cli/kbcli_addon_search.md
pkg/cmd/addon/install.go
pkg/cmd/addon/search.go
pkg/cmd/addon/util.go
pkg/cmd/addon/util_test.go

fix #517
`kbcli addon install` and `kbcli addon search` support auto complete the name of addon. All names of addon are read from the index diractory.

chore: addon install and search support auto complete

---

pkg/cmd/cluster/cluster_test.go
pkg/cmd/cluster/create_subcmds.go
pkg/cmd/cluster/create_subcmds_test.go

fix: add enum check of flags of create cmd

---

pkg/cmd/cluster/config_observer.go
pkg/cmd/cluster/errors.go

fix https://github.com/apecloud/kubeblocks/issues/8730

fix: fix explain-config cmd 

---

docs/user_docs/cli/kbcli_cluster_create_elasticsearch.md
docs/user_docs/cli/kbcli_cluster_delete.md
pkg/cmd/cluster/create_util.go
pkg/cmd/cluster/delete.go

ref apecloud/kubeblocks-addons#1197

chore: remove rbac args

---

docs/user_docs/cli/kbcli_cluster_update.md
go.mod
go.sum
pkg/action/create_test.go
pkg/cluster/cluster_chart_test.go
pkg/cmd/cluster/create_util_test.go
pkg/cmd/cluster/update.go

- fix https://github.com/apecloud/kubeblocks/issues/8910

chore: remove HALT in description and tests

---

docs/user_docs/cli/kbcli_cluster_create.md
docs/user_docs/cli/kbcli_cluster_create_qdrant.md
docs/user_docs/cli/kbcli_cluster_create_rabbitmq.md
docs/user_docs/cli/kbcli_cluster_custom-ops.md
docs/user_docs/cli/kbcli_cluster_update.md
pkg/cmd/cluster/list_logs.go
pkg/cmd/cluster/update.go
pkg/cmd/cluster/update_test.go

- to https://github.com/apecloud/kbcli/issues/564

chore: remove enable-all-logs from kbcli update

---

docs/user_docs/cli/kbcli_cluster_create.md
pkg/cmd/cluster/create.go

fix: improve cluster create comment

---

docs/user_docs/cli/kbcli_cluster_delete.md
pkg/cmd/cluster/delete.go
pkg/util/util.go

fix #578 
if `--force` is specified, every components of the cluster will be added with annotation  "apps.kubeblocks.io/skip-pre-terminate":true

chore: cluster delete support force

---

docs/user_docs/cli/kbcli_cluster_create_kafka.md
pkg/cmd/kubeblocks/kubeblocks_objects.go
pkg/cmd/kubeblocks/kubeblocks_objects_test.go

(cherry picked from commit e1a3c907797159aaffff606e28eb9757114d1e9e) (cherry picked from commit 25db2fabb181f9f5004b55e0ae84783214765c61)

chore: kb uninstall only remove crds that match label (#505)

---

pkg/cmd/cluster/dataprotection.go

* fix https://github.com/apecloud/kbcli/issues/617

chore: fix cluster list-backups output

---

pkg/cmd/cluster/config_ops.go
pkg/cmd/kubeblocks/install.go

- fix https://github.com/apecloud/kbcli/issues/622

chore: skip wait for addons ready if addon list is empty
